travis:
  secure:
    BINSTAR_TOKEN: j0QkicWMcMf+z7NZ8WB0ZginYOJvm8oP7MUS39eGNpbpBis2cjs3LlduKrtU1SmTjhYQmWd04HKk3nCJ0TRkQlcMYYJ6XFoYpvl/I2OcvArEW0koMok2ywnb/jwQNo4m+eTQQrungy1eO/zi28G72hCKZD7DxBpD2BUZJ4VqN1pjJossCzi88dp7KqkToW6AO+mb2GfxgI0UdmIE/baENvGQwe+f4ZZ6IB9soIyPWjRCpDjoFU/tir6lSixxQNdqpzPgBHcKn4NfPp6amW8maMauyTvrxwALSkig2+YxBS5Rp3q/XwFGqlVCdd1n7K0pM670fo/rB8PqhJ6B88irfAlsXmV3Rp7yDTXRvj5UE+ebK6p4v4hx0AXIlhl31Q4fL2aIKrh0YNwEPFAGya8fyERKIcsJsk+avTKWxeFv+F9L0QZTXbAxwSREwpi5hYErT//Yc58LxcdX+wr/+r39m2zZo2V4+HyfYBeM9pIXgB12ZyBeUONN594UGHDbT7sBd42CMfh4QwV3b6zWAq7EL+W4AHFGZga/x3rJdubXhYA0c2n/5/EaI7cKzvPsVp2JnbGIbjfug9LV+3FgpEx31tlMxiRvA9AEDsTlBhtG6q8+IdCBoKGCwdRlBlc5FScHwPxwPVHSDx3jCFMOPpgQ9amzXBAE8eHNo14d4zVp4mg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
