travis:
  secure:
    BINSTAR_TOKEN: hhwggQIbcdQt2PSefhtpDxoBXII0YL5UZCUR1bjpBsS0I8C8GBwBuMfMKFwDpmX+8Batjfl20G1cY+66eN5XTjrL6x6LQKHlfrXpOpqnc0hRoDWlwOUIBaZ2HRkPWclmVEkVAQsDZ4CrZqUY+nK0hRXp7wTS0D1eYhStDk0atWhz0e/LPveU/aexuTxsdod4zw2OBomKtyYswTmxPOEGssPf4bGrjPkeLsT1B4kQHmL9L1h2Zgdvq2CxsGfGQLgjHZ/RaSFSjR0orxfXMGUVPWXTzL4S9lTEp/Z8atZuX9WrHO+sFWV9vsaEbc8SEE4Oi4vggOg3+wZe3CY1CeVli53wyZkL5B3jko85ACXXLFZe++4RufExRZtWBWTXRX+GV2rN7n/3e7kgtpeAgqO7qRNWoIN5QRDnxZP4gTs91l5uiToNc8x0Vr2W2aksaflXiguNxE58aLwkBNgNnO8oD5z4fHBX9k83QAIFuzkDs5cOhhlTrI1jRY85iA7pFFLQLCibgnhb/tsIsPoOTqpEk851wKW9skEgM+KKFv0jeSHsNDUOLXhG2NcyTHL9/Mt7wh353ihZrRmphuuBiO/CQXovQor5iphmxj4je8U4liRgAaprsoFjcjBmdjZLpEyKUc4slhcnvvQGes6MmJRCBTBiePm/5Mn2qSJz6eyEu2k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
